name: bech32
version: 0.2.0-nullsafety.0
description: Library implementing Bitcoins BIP173 (Bech32 encoding) specification in a Flutter friendly fashion.
author: Harm Aarts <harm@aarts.email>
homepage: https://github.com/haarts/bech32

dependencies:
    convert: '>=1.0.0 <=3.0.0'

dev_dependencies:
    test: ^1.16.0-nullsafety
    hex: ^0.2.0-nullsafety
    pedantic: ^1.10.0-nullsafety

environment:
  sdk: ">=2.12.0-0 <3.0.0"
